[project]
name = "simple-yt-dlp-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg>=1.4",
    "typer>=0.21.1",
    "yt-dlp>=2026.2.4",
]
