[project]
name = "Sdlp"
version = "0.1.0"
description = "A wrapper of yt-dlp to simplify its usage."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.14.0",
    "ffmpeg>=1.4",
    "typer>=0.21.1",
    "yt-dlp>=2026.2.4",
]
